### ISSUE TITLE
Write for vector variables

### ISSUE THREAD

**Issue by jacobwilliams** [marshallward/f90nml#10]
Writing the following namelist with the ````write```` method:

````Fortran
&vars
 a%b(2)%c = 1
/
````
produces the following error:

````Python
ValueError: Type <class 'f90nml.namelist.NmlDict'> of NmlDict([('c', 1)]) cannot be converted to a Fortran type.
```` 

It seems to be because the first element of ````b```` is not there.  Note that the ````read```` method worked properly, so the bug is only in ````write````.

Furthermore, if the namelist is instead:
````Fortran
&vars
 a%b(1)%c = 1
/
````
then the ````write```` method produces:

````Fortran
&vars
    a%b%c = 1
/
````
I'm not sure what a compiler would do with this on a namelist read.  To be safe, it should preserve the index of ````b````.

**Comment by marshallward** [comment]
Right... I understand the first error. I only print out derived type indices if I have a list where every element is a `dict`. I can accomodate that to handle `None` without much effort.

The second problem is a little harder to address... There are many instances where I collapse lists of single-element arrays into single values. Mostly because this is how the namelists are handled in most Fortran compilers. AFAIK, all Fortran compilers will serially read through the namelist values and sequentially dump them into the variable (array permitting).

But I can recognise that it could be a nuisance if you create an array of 1, manipulate your namelist, then later add additional entries. So maybe the `x(1)` case should be treated separately from `x`.

(I won't lie, it could be a bit of a pain to code around this case!)

**Comment by marshallward** [comment]
Also, assuming that `a%b(1)%c` and `a%b%c` are functionally equivalent, one can still use the `f90nml.patch` method to preserve the index.

To tell the truth, I think this is a much harder problem to nail down, and might be better moved to a separate issue.

**Comment by marshallward** [comment]
I think the main issue has been solved, so I'm going to close this.
I'll move the `a%b(1)%c` vs `a%b%c` to another issue.
