### ISSUE TITLE
Allow deleting options using `patch` method

### ISSUE THREAD

**Issue by andreas-h** [marshallward/f90nml#106]
I think it would be useful if it were possible to delete namelist options when using `patch`.

For example, I could imagine `nml_patch={'mykey': None}` to delete the `mykey` option from the namelist.

I'm using version 1.0.2.

**Comment by marshallward** [comment]
I agree this would be useful, and has been suggested in the past (#77), with a proposed fix by @sd-joseph.

I haven't invested much time into the problem, partly because the implementation of `patch` is not very flexible; it bascially streams the input directly into a new output, modifying it where possible.  This includes some odd behaviour, like writing hte variable before it knows the value.  So adding and removing values can be a challenge.

But there's clearly interest in getting this working, so I will start from the suggestion in #77 and see if something can work.  I'll probably close this issue and shift discussion to the other one.  Thanks very much for the feedback.

**Comment by marshallward** [comment]
Closing this since it's a duplicate.

**Comment by sd-joseph** [comment]
Unfortunately I never got things into a state suitable for a pull request and haven't been working with the project recently. The workaround in our application code worked well enough to get by with for now.
