### ISSUE TITLE
Another namelist format is not supported

### ISSUE THREAD

**Issue by coreur** [marshallward/f90nml#128]
When I was dealing with some old scientific computing code, I learned a lot of namelists in the following format.
I am not sure if the following namelist format is an old, non-standard format, but this format is well supported by both gfortran and intel visual fortran. However, the f90nml code does not seem to support reading the namelist in this format. Could you add support for this format?

```
$nmlname
 im=46, na=8, nr=21
 nga = 68 
 axi = 16, 12, 9
$end
$nmlname
```

**Comment by marshallward** [comment]
I'm not entirely sure how to interpret this one.

This would be correctly parsed:
```
$nmlname
 im=46, na=8, nr=21
 nga = 68 
 axi = 16, 12, 9
$end
```
but the repeating of the name is a bit odd and more context would be helpful.

For example, repeating the group would be valid:
```
$nmlname
 im=46, na=8, nr=21
 nga = 68 
 axi = 16, 12, 9
$end

$nmlname
nga = 69
$end
```
but in your example it just appears to be incomplete.

I believe that modern compilers will correctly parse the namelist because they typically stop once they reach the end of the group that they were asked to read.  `f90nml`, on the other hand, tried to read (and validate) the entire namelist.  I think that if you tried to read past this group then it would raise an error.

I could perhaps abort a little bit more elegantly, e.g. return the completed namelist and turn the error into a warning.

But if this indeed a valid namelist in some older compiler then that would also be useful.

**Comment by coreur** [comment]
It is not the repeating group. This format was discovered in some input files for an old program. I checked some other input files, some have the repeating name, some do not. I thought it was an old format feature, but it should be some kind of wrong writing. 
Thanks for your reply and your work, they helped me a lot.

**Comment by marshallward** [comment]
Ok thanks for the update.

I will close this issue, let me know if it appears to be more significant.
