### ISSUE TITLE
Parsing error for namelist files

### ISSUE THREAD

**Issue by gaurabkcutk** [marshallward/f90nml#136]
When parsing file[1], I get an error "end-of-file reached before end of namelist". and for file[2] I get an empty data. my code is as follows:

```python3
import f90nml

filename= tarfilename:-3]
unzip(tarfilename,filename)
nml_parser = f90nml.Parser()
nml = nml_parser.read(filename)
data=nml.todict(complex_tuple=True)
```

Resource:
[1]: tarfilename = [user_nl_eam.291713.220502-140244.gz](https://github.com/marshallward/f90nml/files/8664015/user_nl_eam.291713.220502-140244.gz)
[2]: tarfilename =  [user_nl_eam.290096.220427-194610.gz](https://github.com/marshallward/f90nml/files/8664022/user_nl_eam.290096.220427-194610.gz)

**Comment by marshallward** [comment]
Your first file (`user_nl_eam.291713.220502-140244`) has a starting group (`&camexp`) but is missing a closing token (`/`).  So the error is unfortunate and perhaps could be caught and handled different, but I don't think it's wrong.

Your second file (`user_nl_eam.290096.220427-194610`) appears to be missing the namelist group.
```
&grp_name
...
/
```
The parser returns an empty namelist, which is strictly speaking correct since there are no groups.

Do these work in your Fortran application?  They both appear to have some major problems.

**Comment by gaurabkcutk** [comment]
I will check with my team to see if these works on out fortran application and will provide more information. Thank you so much for quick response.

**Comment by marshallward** [comment]
This seems like a straightforward case to me, so I am going to close this.  But please reopen if you think there's anything bigger going on here.
