### ISSUE TITLE
Keep case sensitive names for variables and groups

### ISSUE THREAD

**Issue by danielabdi-noaa** [marshallward/f90nml#145]
The keys for namelists and variable names are currently converted to be lower case unless specifically requested to be uppercase.
```Python
if self.uppercase:
      v_name = v_name.upper()
```
Is it not better to just keep whatever keys the user feeds into the program instead of converting it?
I know fortran is case insensitive, but it would be more useful for me if it can just keep the cases I feed into it.
Also it seems getitem() etc are case insensitive, which can still be maintained if both keys are lowercased.

**Comment by marshallward** [comment]
I agree it would be better, but it would require a significant reworking of the parser.

The decision was made at the time to simplify the parser.  If I ever re-write the parser, I will do as you suggest, but unfortunately it would be a bigger task than I can commit to at the moment.

**Comment by danielabdi-noaa** [comment]
Thanks for the quick response!

**Comment by marshallward** [comment]
I should mention that the [flint](https://github.com/marshallward/flint) project does preserve case in the way that you suggest, and I would like to do something similar with f90nml.  It is a bit slower though, because it wraps everything in a `Token` class.

I've also been experimenting with [DFAs](https://en.wikipedia.org/wiki/Deterministic_finite_automaton) in a project (currently private) which are many times faster than the current scanner in either flint or f90nml.  So hopefully this work will make its way into those projects sometime soon.
