### ISSUE TITLE
String variables mistmatch

### ISSUE THREAD

**Issue by vkrokhin** [marshallward/f90nml#15]
Hello!

'f90nml' - as a great thing! Thanks!

I found some bugs, I suppose.

For example, if we have in namelist

&data_control_on_pressure_levels

params_on_pressure_levels = HGT, TMP, UGRD, VGRD, RH,

/

then on output we get

['HGT', True, 'UGRD', 'VGRD', 'RH']

At second, if 

&data_control_on_pressure_levels

params_on_pressure_levels = HGT, FTMP, UGRD, VGRD, RH,

/

then

['HGT', False, 'UGRD', 'VGRD', 'RH']

I think, that bug in the fpy.py, in pybool function.

“TMP” is not “True”.

Test for first symbol is not good.

Thanks!

With regards,

Vladimir Krokhin, researcher, PhD,

Department of Meteorology and Tropical Cyclones,

Far Eastern Regional Hydrometeorological Research Institute,

Vladivostok, Russia.

**Comment by marshallward** [comment]
Thanks for submitting the issue, I'll add some of our correspondence from the email.

The core issue is that f90nml cannot predict the type of a value, which would normally be resolved in the fortran program itself.

The parser tries to interpret the value by testing it as one of the types. First integer, then float, complex, logical, and finally string. It's not perfect, but usually does not cause serious problems.

If you use quote delimiters, then strings are unambiguous. But if you do not use them (which is valid Fortran), then it fails if the string begins with a 't' or an 'f'.

This is because any value starting with F or .F is a valid representation of logical False (which is often written as .false.). Similar rules apply to logical True.

Testing for the first symbol can be problematic, but it is consistent with Fortran's rules for logicals.

In this case, f90nml cannot predict that FTMP is meant to be a string or a boolean variable. If it were written with quote delimiters ('FTMP') then it would be clear, but without them it is not explicit.

----

You can solve your case by replcaing FTMP and TMP with 'FTMP' and 'TMP' in your namelist, but it would be better to give users more control over this.

One solution is to check for arrays, and ensure that all types match. In this case, it could be possible to assume Strings based on the other values, although that could also be a problem if all the values began with 't' or 'f'.

Another is to explicitly match 't' or 'true', based on a control flag, although that could also fail if that is the actual string value.

Also, one could submit a "type reference" where you, for example, append a dict like this:

    my_types = { ('data_control_on_pressure_levels', 'params_on_pressure_levels'): string}

But I'm still not sure which one is best.

When I get some time, I will try to implement something that works. But any feedback you have would be very helpful.

**Comment by marshallward** [comment]
I've modified the rules for non-delimited string parsing.

The default behaviour is now as follows:
`True`: `true`, `.true.`, `t`, `.t.`
`False`: `false`, `.false.`, `f`, `.f.`

To restore the original (Fortran standard) behaviour, which only looks at the first two characters, use the `strict_logical` flag in the `read` program.

I will close this ticket, but please feel free to re-open it if it's not working.
