### ISSUE TITLE
Derived type patch doesn't replace values, it just adds them

### ISSUE THREAD

**Issue by naught101** [marshallward/f90nml#35]
`f90nml.patch` doesn't actually modify any of the existing values, if just adds new copies according to the patch.

I'm not sure whether this is a huge problem - it doesn't appear to be a problem for the model I'm patching namelist files for, but it might be for others. Either way, it kind of leaves the namelist a bit messy, and could get bad if you're doing sequential edits.

Of course, removing lines with comments on them makes for potential data loss, so perhaps this in contingent on f90nml supporting comments. Is that ever likely to happen?

**Comment by marshallward** [comment]
That's definitely not the intended behaviour, and the tests aren't showing any problems.

Can you provide an example showing the problem that you are seeing?

**Comment by marshallward** [comment]
Is this related to issue #38 in any way?

**Comment by marshallward** [comment]
OK, thanks for this.  You are using it correctly, and this is a real bug, one that I had forgotten about.

Currently `patch` does not work correctly with derived types (`filename%met`).  In fact, I'm amazed that it worked at all.

The `patch` code was difficult to write, and I avoided dealing with derived types in order to get something working.  But I never returned to this problem.

This one is more recursive, and could be a little difficult to get working, but it needs to be done.  I will have a look at it this week and try to get it working.

Thanks for providing this example and letting me know about the problem.

**Comment by naught101** [comment]
Ah, yep, you're right. It works fine for simple values.

**Comment by marshallward** [comment]
Can you check the latest comment to see if it works?

**Comment by naught101** [comment]
```{bash}
$ scripts/edit_cable_nml.py edit cable_old.nml -o cable_new.nml "filename%met=blah.txt"
Namelist cable_old.nml edited and saved as cable_new.nml

$ cat cable_new.nml 
&cable
   filename%met = 'blah.txt'
&end
```

Success! :) Thanks!
