### ISSUE TITLE
maximum length of variable names

### ISSUE THREAD

**Issue by jacobwilliams** [marshallward/f90nml#41]
I'm seeing an issue with very long variable paths:
```
&a
bbbbbbbbbbbb%ccccccccccccccccccccccc%ddddddddddddddd%eeeeeeeeeeee = 1
bbbbbbbbbbbb%ccccccccccccccccccccccc%ddddddddddddddd%eeeeeeeeeee = 2
bbbbbbbbbbbb%ccccccccccccccccccccccc%ddddddddddddddd%eeeeeeeeee = 3
/
```
when I read/write it comes out as:
```
&a
    bbbbbbbbbbbb%ccccccccccccccccccccccc%ddddddddddddddd%eeeeeeeeeeee =
    bbbbbbbbbbbb%ccccccccccccccccccccccc%ddddddddddddddd%eeeeeeeeeee = 2,
    bbbbbbbbbbbb%ccccccccccccccccccccccc%ddddddddddddddd%eeeeeeeeee = 3,
/
```

**Comment by jacobwilliams** [comment]
Oops, sorry, this is the `colwidth` property, isn't it?

Interestingly, it seems to read in very long strings just fine. So:
```fortran
a%b = '11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111',
```
is fine. Is it only if the variable name pushes it past the max number of characters?

**Comment by marshallward** [comment]
It's related to `colwidth`, but whatever it is, it's definitely a bug :).  The output looks OK when I increase `colwidth`.

The column width is not a hard limit; it does allow values to extend past the `colwidth` value.  But there might be some off-by-one error in here somewhere.  I remember the wordwrap stuff was a bit tricky at the time.

The main reason for the line wrap was because some models would explicitly add vectors of hundreds of values, and the compilers would chop off the values if the line was too long :).  I figured that it was ok to exceed `colwidth` by a bit if necessary.

My version is not appending commas, is this something that you turned on?

**Comment by jacobwilliams** [comment]
I don't think I did anything special with the commas. I'm just using:
```python
data = f90nml.read('long.nml')
with open('long_resaved.nml','w') as f:
    data.write(f, force=True)
```
It looks like `colwidth` is also used for breaking up vector elements across multiple lines? In my case, I would like to set a large (or infinite) length for reading the variables, but still have a shorter width for printing (just for aesthetic reasons). But, that's not really a big deal, so feel free to ignore that suggestion. :)

**Comment by marshallward** [comment]
Looks like the problem is very long variable names.  The values are aligned to the end of the variable name string (+ spacing, headers, etc).  Since the first entry here is 72 columns, there's no room left to print out the actual variables.  Since the second and third entries are shorter, and values are only one character long, they fit without any problem.

Replacing `1` with a vector `1, 2, 3` showed the same problem, with blank lines below the variable name.

I am not sure how to deal with this case, I may need to abandon alignment to the variable name and just do some indentation on the next line.

**Comment by marshallward** [comment]
I added something which (sort of) fixes this bug.  Only took 4 months!  Can you give it a try?

**Comment by jacobwilliams** [comment]
Awesome! In my case I just set `colwidth=256` and then forgot all about it. I'll test the fix... probably won't be until next week though.

**Comment by jacobwilliams** [comment]
Seems to work great! Thanks!
