### ISSUE TITLE
Parser crashes for namelist containing consecutive commas

### ISSUE THREAD

**Issue by knedlsepp** [marshallward/f90nml#65]
The following example produces a StopIteration exception. Binaries produced with gfortran however accept the namelist just fine. 

### test.nml
```
&GROUP
  VAR(1:2)=10,20,,
/
```
### test.py
```
import f90nml
nml = f90nml.read('test.nml')
```

**Comment by marshallward** [comment]
Thanks, I can reproduce this.  As you probably guessed, the two commas are being interpreted as a third null value, which is failing because the index iterator has already finished.

There are two intepretations here, one as a null value and also as just an empty comma-separated declaration.

I'll try to fix this up, maybe just an early abort of the index iterator loop will solve it.

**Comment by marshallward** [comment]
I have something working.  But interestingly, this would produce a runtime error in Fortran:
```
&group
    var(1:2) = 10, 20, 30,
/
```
I'll try to see if I can try to respect this as a bad namelist.

**Comment by marshallward** [comment]
This should now be fixed in master.

**Comment by knedlsepp** [comment]
Thank you very much for dealing with this so fast!
