### ISSUE TITLE
Help strings for command line interface

### ISSUE THREAD

**Issue by warrickball** [marshallward/f90nml#72]
This is a very useful tool! I have several feature requests, the first of which is for the command line interface to include the help strings that are in the documentation. i.e. the CLI current doesn't explain the arguments:

    $ f90nml -h
    ...
    positional arguments:
      input
      output

    optional arguments:
    ...
      --group GROUP, -g GROUP
      --variable VARIABLE, -v VARIABLE
      --patch, -p
      --format FORMAT, -f FORMAT
      --output OUTPUT, -o OUTPUT

whereas the documentation does (in [`cli_flags.rst`](https://github.com/marshallward/f90nml/blob/master/docs/source/cli_flags.rst)).

I've prepared a pull request in which I've copied the text from the documentation to `cli.py`. It's my first PR so I'm not sure what's customary. Should I just go ahead and make the PR?

**Comment by marshallward** [comment]
Thanks very much, the CLI is relatively new and not used much from what I can tell, so I really appreciate the feedback.  I agree that the CLI help page could use some help, and any PR that you have would be most welcome.

Ideally it would be good to pull these strings from a separate file, or the file could be generated from Python source, although I'm not sure how to do that at the moment.  But your pull request is a good start, and your `cli_doc` branch is already a major improvement, so feel free to submit it.

----

If you are interested for some context -

The `cli_doc.rst` file is used by sphinx to build a man page which would be available via `man f90nml`, as well as the [Sphinx documentation](http://f90nml.readthedocs.io/en/latest/cli.html).

In practice, there isn't a safe way to install man pages via `pip`, mostly because it requires assumptions about one's directory structure, and the ideal solution is to connect f90nml with each distributions (Red Hat, Debian, etc) which do provide this structure and allow one to safely install the man page.

This is kind of a side issue though.  Even in the absence of a man page, `f90nml -h` could be more informative.
