### ISSUE TITLE
How to parse string with namelist file content

### ISSUE THREAD

**Issue by sound-fx** [marshallward/f90nml#76]
What is the proper way to get a Namelist from a string with the content of a namelist file?

I've done this using the Parser.readstream method:
```
namelist_content = """
 &My_data
   an_array = 3., 5., 7.
   my_index = 2
 /   
"""
namelist=parser.readstream(namelist_content, f90nml.Namelist())
```
Now that the Parser.readstream method is nominally private (i.e., renamed to Parser._readstream), this technique seems sneaky.  What's the preferred way?

**Comment by marshallward** [comment]
This is a good question, and I don't really know the answer, which is why issue #28 is still open.

`readstream()` made the question somewhat moot since it was possible to use this function, although it was a bit clumsy.  I was a bit concerned about this issue when I renamed it to be nominally private, but felt like it might prompt us to resolve the issue. (Success?!?)

Also, some of the implementation arguments around #28 are no longer relevant since we are no longer using `shlex` for parsing, which would have caused some redundant back-and-forth conversion between streams and strings.

Ideally I would love for `f90nml.read` to be super-smart and just interpret anything to produce a namelist, but I don't know if I'm prepared for that solution.

I looked around at other parsers and there isn't much consistency here.  I'm happy to take ideas and suggestions here, even if it's just adding a `readstring` function.

**Comment by marshallward** [comment]
I think my preference here is to add `reads()`, mostly because JSON uses `load`/`loads` and it is probably the closest cousin to a namelist.

**Comment by sound-fx** [comment]
Between a super-smart `read()` and a `reads()`, I don't have a preference.

Adding `reads()`, your preference, has the advantage that it advertises the functionality, reducing the need for consulting the documentation or the source code or trial-and-error.

**Comment by marshallward** [comment]
I've added the `reads` function.  Can you give it a try?

I am thinking of renaming this to `readstring`.  While it's nice to resemble JSON and some other parsers, I feel like `read` and `reads` should be a little more distinguishable.

**Comment by marshallward** [comment]
It also occurs to me that `_readstream` now takes an iterable, rather than a stream, and should probably be renamed.
